sudo: required
services:
 - docker
before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"
     
before_install:
 - docker build -t kldocker01/docker-react -f Dockerfile.dev .
    
script:
 - docker run kldocker01/docker-react npm run test -- -- coverage