sudo: required
services:
 - docker
script:
  - 'gem install bundler'
  - 'rake spec'
     
before_install:
 - docker build -t kldocker01/docker-react -f Dockerfile.dev .
    
script:
 - docker run kldocker01/docker-react npm run test -- -- coverage